---
repository: HackPeel/peelhacks.github.io
include: ["index.html"]

# Homepage settings
splash_title: 'hack::peel'
splash_subtitle: 'A Peel-wide hackathon for students to compete, collaborate and learn'
homepage_banner_image: photos/home_banner.jpg
display_ad: true


# Links for the navbar
navs:
  -
    name: FAQ
    link: "/#faq"
  -
    name: Events
    link: "/#timetable"
  -
    name: Sponsors
    link: '/#sponsors'
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"
  -
    name: The team
    link: "/#team"


# Social media links included on the splash page
# socials:
#   -
#     icon: "facebook-white.svg"
#     name: Facebook
#     url: "https://facebook.com/hackpeel"
#   -
#     icon: "twitter.svg"
#     name: Twitter
#     url: "https://twitter.com/hackpeel"
#   -
#     icon: "github-mark.png"
#     name: GitHub
#     url: "https://github.com/HackPeel"

email: contact@hackpeel.ca


sass:
  style: compressed
  sass_dir: _sass